config/routes.rb
Rails.application.routes.draw do
 

    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get '/bolus',  to: 'static_pages#bolus'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get  '/users',   to: 'users#index'
    get 'users/:id/edit/diabsettings', to: 'users#edit_diabsettings', as: :edit_diabsettings
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    post '/diaryentry',  to: 'diary_entries#create', as: :diary_entry
    get '/diaryentry',  to: 'diary_entries#new'

    resources :users, except: [:new] do
      resources :diabetes_settings, only: [:new, :create, :edit, :update, :index]
      resources :bu_factors, only: [:new, :create, :edit, :update, :index]
    end
      
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]  
    resources :diary_entries
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end

  def bolus
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | My Diabetes Diary App Ruby on Rails</title>
  </head>
  <body>
    <h1>My Diabetes Diary</h1>
    <p>The Diabetes Diary App is an App to record your daily Diabetes management it includes a Bolus Calculator which you can use on the fly. If You sign up as a Diabetes Patient you can program your KH/BE Faktoren according to Your treatment plan, your correction bolus rule and your your ideal blood sugar interval. When You use it for calculating Your Insulin according to what you ate or calculating a correction bolus on the basis of a hyperglycämic Blood sugar value, Your data is automatically recorded to your Diabetes Diary. When You enter a blood sugar the App will record it. If it is too high, it will propose You a correction bolus according to Your Treatment Plan. If it is too low it will recommend You to eat fast carbohydrates according to your treatment plan.  </p>
  </body>
</html>

app/views/static_pages/bolus.html.erb
<% provide(:title, "Bolus Rechner") %>

<%#= javascript_include_tag "Bolus_Rechner"%>


           
            <h1 class="text-center">My Diabetes Diary</h1>
  
      
        
            <h2 class="text-center heading-bolus">Bolus Rechner</h1>
            <h4 class="text-center text-muted" id="Uhrzeit"></div> </h4>
          
     
    
    

      <div class="container">
  <form>
    <div class="form-group row top buffer">
    
      <label for="be" class="offset-sm-4 col-sm-2 col-form-label text-left">Carbohydrates(BU) eaten</label>
      <div class="col-sm-2">
        <input type="number" min="0" class="form-control" id="be" name="be">
        
      </div>
    </div>
    <div class="form-group row">
      <label for="faktor" class="offset-sm-4 col-sm-2 col-form-label">BU-Faktor</label>
      <div class="col-sm-2">
        <input type="number" min="0" class="form-control" id="faktor" name="faktor" value="">
        
        </div>
       
    </div>
    <div class="row">
      <div class= "offset-sm-5 col-sm2 ">
        <button type="button" class="btn btn-primary btn-md" onclick="insulinBerechnen()">Insulin berechnen</button>
      </div>
      </div>
     <div class="row top-buffer"> 
      <div class="offset-sm-4 col-sm-4 lead bg-warning">
            
              Sie müssen <strong id="insulin"></strong> U (Insulineinheiten) spritzen
            
      </div>
      </div>
      </div>
  </form>
  
  
 




  

app/views/static_pages/bolus.html_off.erb
<% provide(:title, "Bolus Rechner") %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | My Diabetes Diary App Ruby on Rails</title>
  </head>
  <body onload="timeFakt()">
    <h1>My Diabetes Diary</h1>
    <header>
      
            <h1 class="text-center">Bolus Rechner</h1>
            <h4 class="text-center text-muted" id="Uhrzeit"></h4>
       
    </header>
    <article>

      <form class="">
        <div class="form-group">
          <div class="row">
            <div class="col-md-1 col-md-offset-2">


              <label for="be">BE</label>
            </div>
            <div class="col-md-3">
              <input type="number" id="be" class="form-control" name="be" />

              <small id="be-info" class="form-text text-muted">
              (Hier können Sie die gegessenen Kohlenhydrate in Broteinheiten eingeben.) 
              </small>
            </div>
          </div>
        </div>



        <div class="form-group" >

          <div class="row">
            <div class="col-md-2 col-md-offset-1">
              <label for="faktor">aktueller BE-Faktor </label>
            </div>
            <div class="col-md-3">
              <input type="number" id="faktor" class="form-control" name="faktor" value="" />


              <small id="faktor" class="form-text text-muted">
                (Hier können Sie den aktuellen BE-Faktor ändern, wenn nötig.) 
                </small>
            </div>

            <div class="col-md-2">
              <button class="btn btn-sm btn-danger" type="button" onclick="faktorAendern()">BE-Faktor ändern</button>
            </div>

            <div class="col-md-3">

            </div>


          </div>

        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-3">
            <button type="button" class="btn btn-primary btn-lg" onclick="insulinBerechnen()">Insulin berechnen</button>
          </div>
        </div>

        <p> </p>
        <div class="row">
          <div class="col-md-5 col-md-offset-3">
            <p class="lead bg-warning">

              Sie müssen <strong id="insulin"></strong> U (Insulineinheiten) spritzen
            </p>
          </div>
        </div>
      </form>




    </article>
  </div>
  <%= javascript_include_tag "Bolus_Rechner"%>
  </body>

</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>


<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | My Diabetes Diary App Ruby on Rails</title>
  </head>
  <body>
    <h1>My Diabetes Diary</h1>
    <p>Contact Page for the  Diabetes Diary App </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | My Diabetes Diary App Ruby on Rails</title>
  </head>
  <body>
    <h1>My Diabetes Diary</h1>
    <p>Help Page for the  Diabetes Diary App </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the My Diabetes Diary App</h1>
  <h2>
    This is the home page for the
    My Diabetes Diary application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>