config/routes.rb
Rails.application.routes.draw do
 

    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get '/bolus',  to: 'static_pages#bolus'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get  '/users',   to: 'users#index'
    get 'users/:id/edit/diabsettings', to: 'users#edit_diabsettings', as: :edit_diabsettings
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    post '/diaryentry',  to: 'diary_entries#create', as: :diary_entry
    get '/diaryentry',  to: 'diary_entries#new'

    resources :users, except: [:new] do
      resources :diabetes_settings, only: [:new, :create, :edit, :update, :index]
      resources :bu_factors, only: [:new, :create, :edit, :update, :index]
    end
      
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]  
    resources :diary_entries
  end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
    My Diabetes Diary
    by <a href="https://github.com/acousma82">Sebastian Peter</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<div class="container">
      <nav class="navbar fixed-top navbar-expand-lg navbar-inverse bg-inverse ">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
      <div class="navbar-brand">My Diabetes Diary</div>

      
        <ul class="navbar-nav navbar-right">
          <li class="nav-item">
            <%= link_to "Home",   root_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Help",   help_path, :class => "nav-link"%>
          </li>
          <% if logged_in? %>
              <% if current_user.admin? %>
                <li class="nav-item"><%= link_to "Users", users_path, :class => "nav-link"%></li>
                <% end %>
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" >
                    Diabetes Functions
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                  <%= link_to "New Diary Entry", new_diary_entry_path, :class => "dropdown-item" %>
                  
                  <div class="dropdown-divider"></div>
                  <%= link_to "Diabetes Settings", new_user_diabetes_setting_path(current_user), :class => "dropdown-item" %>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" >
                    Account 
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                  <%= link_to "Profile", current_user, :class => "dropdown-item" %>
                  <%= link_to "Settings", edit_user_path(current_user), :class => "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Log out", logout_path, method: :delete, :class => "dropdown-item" %>
                  </div>
                </li>
          <% else %>
                <li class="nav-item">
                  <%= link_to "Bolus Rechner",  bolus_path, :class => "nav-link" %>
                </li>
                <li class="nav-item"><%= link_to "Log in", login_path, :class => "nav-link" %></li>
          <% end %>
        </ul>
      
     </nav>
     </div>
    </header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>

<%= render 'layouts/shim' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]--><!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<%# application.html.erb is the basic html for all other html on the site%>
<!DOCTYPE html>
<html>
  <head>
   <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  
  </head>
  <body>
  <%= Gon::Base.render_data %>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %> 
         
    
   
    <%= debug(params) if Rails.env.development? %>  
    </div>
  </body>
  
</html>